albert_homepage:
    path:     /
    defaults: { _controller: AlbertBundle:Default:index }
    
albert_hello:    
    path:     /{name}
    defaults: { _controller: AlbertBundle:Default:sayHello }
    
albert_check_Twig:    
    path:     /Twig/{name}
    defaults: { _controller: AlbertBundle:Default:checkTwig }
